extraction:
  cpp:
    prepare:
      packages:
        - "cmake"
    configure:
      command: "cmake -S . -B build -DBUILD_QCEC_TESTS=ON -DGIT_SUBMODULE=OFF"
    index:
      filters:
        - exclude: "src/extern/qfr/extern/dd_package/extern/googletest/*"
        - exclude: "src/extern/json/*"
        - exclude: "src/extern/pybind11/*"
        - exclude: "src/extern/pybind11_json/*"
        - exclude: "src/scripts/*"
      build_command: "cmake --build build --parallel 4"
