path_classifiers:
  test:
    - test
    - src/extern/qfr/test
    - src/extern/qfr/extern/dd_package/test
    - src/extern/qfr/extern/dd_package/extern/googletest
    - src/scripts
  library:
    - src/extern/json
    - src/extern/pybind11
    - src/extern/pybind11_json

extraction:
  cpp:
    prepare:
      packages:
        - "cmake"
    configure:
      command: "cmake -S . -B build -DBUILD_QCEC_TESTS=ON -DGIT_SUBMODULE=OFF"
    index:
      build_command: "cmake --build build --parallel 4"
