path_classifiers:
  test:
    - test
    - extern/qfr/test
    - extern/qfr/extern/dd_package/test
    - scripts
  library:
    - extern/qfr/extern/dd_package/extern/googletest
    - extern/qfr/extern/json
    - extern/qfr/extern/pybind11
    - extern/qfr/extern/pybind11_json

extraction:
  cpp:
    prepare:
      packages:
        - cmake
    configure:
      command:
        - cmake -S . -B build -DGIT_SUBMODULE=OFF -DBUILD_QCEC_TESTS=ON -DBUILD_QFR_TESTS=ON -DBUILD_DD_PACKAGE_TESTS=ON
    index:
      build_command:
        - cmake --build build --parallel 4
