language: cpp
os: linux
dist: focal

jobs:
  include:
    - os: linux
      dist: focal
      compiler: "gcc"
      env: BUILD='Debug' CC=gcc CXX=g++ COVERAGE=1 COV_EXE=gcov
      addons:
        apt:
          packages:
            - cmake
            - ninja-build
            - lcov

    - os: linux
      dist: focal
      compiler: "gcc"
      env: BUILD='Release' CC=gcc CXX=g++ COVERAGE=0
      addons:
        apt:
          packages:
            - cmake
            - ninja-build

    - os: linux
      dist: focal
      compiler: "gcc"
      env: BUILD='Release' CC=gcc-10 CXX=g++-10 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - cmake
            - ninja-build
            - gcc-10
            - g++-10

    - os: linux
      dist: focal
      compiler: "clang"
      env: BUILD='Release' CC=clang-11 CXX=clang++-11 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - cmake
            - ninja-build
            - clang-11

    - os: osx
      osx_image: xcode12
      compiler: "clang"
      env: BUILD='Release' CC=clang CXX=clang++ COVERAGE=0
      addons:
        homebrew:
          packages:
            - cmake
            - ninja

    - os: osx
      osx_image: xcode12
      compiler: "gcc"
      env: BUILD='Release' CC=gcc-10 CXX=g++-10 COVERAGE=0
      addons:
        homebrew:
          packages:
            - cmake
            - ninja
            - gcc@10

    - os: windows
      env: BUILD='Release' CC=gcc CXX=g++ COVERAGE=0

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    export PATH="$(brew --prefix llvm)/bin:$PATH";
    fi
  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version
  - cmake --version

before_script:
  - mkdir -p build && cd build
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cmake .. -G "Visual Studio 15 2017" -A x64 -LA -DCMAKE_BUILD_TYPE=${BUILD} -DCOVERAGE=${COVERAGE} -DBUILD_QCEC_TESTS=ON
    else
      cmake .. -G Ninja -LA -DCMAKE_BUILD_TYPE=${BUILD} -DCOVERAGE=${COVERAGE} -DBUILD_QCEC_TESTS=ON -DBUILD_QCEC_BINDINGS=ON
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      cmake --build . --config ${BUILD} --target INSTALL;
    else
      cmake --build . --config ${BUILD} --target qcec;
      cmake --build . --config ${BUILD} --target qcec_example;
      cmake --build . --config ${BUILD} --target qcec_test;
      sudo cmake --build . --config ${BUILD} --target install;
    fi
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      cd test/${BUILD};
      ./qcec_test.exe;
      cd ../../;
    else
      cd test;
      ./qcec_test;
      cd ..;
    fi

after_success:
  - |
    if [[ -n "${COV_EXE}" ]]; then
      # Create lcov report
      lcov --gcov-tool ${COV_EXE} --capture --directory . --base-directory . --output-file coverage.info
      lcov --remove coverage.info '/usr/*' '*/extern/*' '*/EquivalenceCheckingResults*' --output-file coverage.info # filter system-files
      lcov --list coverage.info # debug info
      # Uploading report to CodeCov
      bash <(curl -s https://codecov.io/bash) -f coverage.info -t 7473cb74-fb9e-4c19-90b6-0b5aab6ccdfc || echo "Codecov did not collect coverage reports"
    fi
